# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    desc "Run Tests"
    lane :tests do
        xcclean
        run_tests(
            scheme: "Bootstring-iOS",
            devices: ["iPhone X"]
        )
        run_tests(
            scheme: "Bootstring-macOS",
            destination: "platform=macOS"
        )
        run_tests(
            scheme: "Bootstring-tvOS",
            devices: ["Apple TV"]
        )
    end

    desc "Build Carthage"
    lane :build_carthage do |options|
        Action.sh "cd .. && carthage build --no-skip-current"
    end

    desc "Build Cocoapods"
    lane :build_cocoapods do |options|
        Action.sh "cd .. && pod lib lint --verbose  --no-clean"
    end
end
